---
images:
  bash: registry.access.redhat.com/ubi8-minimal:latest
  openshiftCli: registry.access.redhat.com/openshift3/ose-cli:latest

annotations:
  tekton.dev/pipelines.minVersion: "0.17.0"
  tekton.dev/tags: cli
  tekton.dev/displayName: "openshift client"
