---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: openshift-client
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{- if .Values.annotations }}
  annotations:
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: >-
    This task runs commands against the cluster provided by user
    and if not provided then where the Task is being executed.

    OpenShift is a Kubernetes distribution from Red Hat which provides oc,
    the OpenShift CLI that complements kubectl for simplifying deployment
    and configuration applications on OpenShift.

  workspaces:
    - name: manifest_dir
      optional: true
      description: >-
        The workspace which contains kubernetes manifests which we want to apply on the cluster.
    - name: kubeconfig_dir
      optional: true
      description: >-
        The workspace which contains the the kubeconfig file if in case we want to run the oc command on another cluster.

  params:
    - name: SCRIPT
      description: The OpenShift CLI arguments to run
      type: string
      default: "oc help"
    - name: VERSION
      description: The OpenShift Version to use
      type: string
      default: "latest"

  stepTemplate:
    env:
{{- $variables := list
      "params.SCRIPT"
      "params.VERSION"
      "workspaces.manifest_dir.bound"
      "workspaces.manifest_dir.path"
      "workspaces.kubeconfig_dir.bound"
      "workspaces.kubeconfig_dir.path"
}}
{{- include "environment" ( list $variables ) | nindent 6 }}

  steps:
{{- include "load_scripts" ( list . "oc-" ) | nindent 4 }}

    - name: oc
      image: {{ .Values.images.openshiftCli }}
      env:
        - name: HOME
          value: /tekton/home
      command:
        - /scripts/oc-client.sh
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts

  volumes:
    - name: scripts-dir
      emptyDir: {}
