---
name: test

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Install Catlin linting tool
      - name: Install Catlin linting tool 
        run: |
          git clone https://github.com/tektoncd/catlin
          cd catlin
          make bin/catlin
          sudo cp bin/catlin /usr/local/bin
          catlin --help

      # run Catlin linting
      - name: Run Catlin linting
        run: |
          helm template task-oc . > task-oc.yml
          catlin validate task-oc.yml

  test-e2e:
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        pipeline-version:
        - v0.44.5
        - v0.47.5
        - v0.50.5
        - v0.53.2
        - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REGISTRY_REDHAT_USERNAME }}
          password: ${{ secrets.REGISTRY_REDHAT_TOKEN }}

      - uses: azure/setup-helm@v3

      # instantiate a KinD (Kubernetes in Docker) cluster, installs `kubectl` and configures the
      # `kubeconfig` to reach the local cluster
      - uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind
          wait: 120s

      # installs Tekton Pipelines and `tkn` command line, including a local Container-Registry with
      # settings to reach it during testing
      - uses: openshift-pipelines/setup-tektoncd@v1
        with:
          pipeline_version: ${{ matrix.pipeline-version }}

      # running end-to-end test target
      - name: test-e2e
        run: make test-e2e
